### ISSUE TITLE
Tikz image generation

### ISSUE THREAD

**Issue by xfbs** [gettalong/webgen#10]
I'm currently using webgen for a personal project and I've really come to like it. I do feel that I could do a bit to improve the tikz support tho. So here's some questions/ideas:

* Why are you calling `pdflatex` with the `-shell-escape` flag? That would be a potential security issue.
* Would it make sense to add support for xelatex/lualatex? They natively support system fonts with `fontspec`.
* Would it make sense to use `\documentclass[tikz]{standalone}`, in `datawebgen/passive_sources/templates/tikz.template`, because like the you don't need `pdfcrop` and you get a lot of useful packages pre-loaded?
* Would it make sense to support generating `*.svg` images using `pdf2svg` from the Tikz drawings?

**Comment by gettalong** [comment]
Thanks for the issue and the pull requests - I just wanted to let you know that it will take some time for me to look at the things you propose but from a quick look-through they seem okay and valid.

**Comment by xfbs** [comment]
Hey, that's okay. I'm just contributing back the things I've tweaked on my end :)

**Comment by gettalong** [comment]
As for `-shell-escape`: I really don't know anymore :( But since webgen is normally run only locally it shouldn't be that much of a security problem.

I have integrated all your pull requests - thank you!
