### ISSUE TITLE
[ERROR] invalid byte sequence in US-ASCII

### ISSUE THREAD

**Issue by MatheusRV** [gettalong/webgen#15]
I am developing a benchmark of the page generation time of the different SSGs, webgen is not conducting as expected. It returns an invalid byte sequence error in US-ASCII when I run the webgen generate command. I am creating the pages within SSG as follows:

```
src/posts/2019-09-20-10.page
---
created_at: 2019-09-20
title: 2019-09-20-10
---
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum euismod luctus massa. Pellentesque porta augue non varius semper. In vitae pulvinar dolor. Nunc erat sem, facilisis eu augue in, aliquam viverra magna. Quisque porttitor sodales diam, a vestibulum sem semper vel. Integer tempus quam eu ex egestas, sed auctor neque venenatis. Fusce mattis metus pellentesque iaculis euismod. Vestibulum a dictum lectus, a porta odio. Etiam sit amet lobortis lorem. Mauris iaculis ornare risus, at dictum nullam.
```

I hope to get some support to add webgen to the tests along with 13 other SSGs

**Comment by gettalong** [comment]
I created a test website with `webgen create website test` and then put the contents you provided into a page file. The output of `webgen`:

~~~
INFO  Generating website...
INFO  [create] </>
INFO  [create] </test.html>
WARN  Default template 'default.template' not found in root directory!
WARN  Default template 'default.template' not found in root directory!
INFO  ... done in 0.10 seconds
~~~

There was no error. Maybe there is another problem with the whole setup? Can you provide a full sample website that fails with the given error?

**Comment by MatheusRV** [comment]
https://github.com/MatheusRV/StaticSiteGeneratorBenchmarks/tree/master/frameworks/Ruby/webgen

docker copy package inside src where project is located.

**Comment by gettalong** [comment]
When I download a ZIP of your repository, change into the `StaticSiteGeneratorBenchmarks-master/StaticSiteGeneratorBenchmarks-master/frameworks/Ruby/webgen/src` directory and run `webgen`, it works without any errors.

**Comment by MatheusRV** [comment]
I'm using build.sh to create content.

**Comment by gettalong** [comment]
There is a problem with the `build.sh` script. If I run it, it will create a `src/posts` folder. However, the real source directory is `src/src`. If I move the folder to the correct location and start webgen manually, the website is generated without errors.

**Comment by MatheusRV** [comment]
Force UTF8 in shell script solve. Tks alot.
