### ISSUE TITLE
CommonMark compliant markdown parser

### ISSUE THREAD

**Issue by noraj** [gettalong/webgen#16]
Well there are 3 markdown parsers, but sadly none of them is [CommonMark](https://commonmark.org/) compliant. It would be good to have one like https://github.com/gjtorikian/commonmarker

**Comment by gettalong** [comment]
If you need the mentioned one, please put the following in the `ext/init.rb` file which registers it as "common_marker":

~~~ ruby
require 'commonmarker'

website.ext.content_processor.register('common_marker') do |context|
  context.content = CommonMarker.render_html(context.content, :DEFAULT)
  context
end
~~~

**Comment by noraj** [comment]
Thank you!
