### ISSUE TITLE
private method `load' called for Psych:Module

### ISSUE THREAD

**Issue by DamienRobert** [gettalong/webgen#7]
There is a strange bug when using webgen with psych 2.0.13, when calling `webgen` I get an error:
webgen encountered a problem:
private method `load' called for Psych:Module

If I uninstall psych 2.0.13 to use psych 2.0.8 (or simply add "gem 'psych', '2.0.8'" to webgen/cli.rb), webgen can start correctly. Of course 'load' is a valid method for YAML, so what happen is that according to $LOADED_FEATURES, when using psych 2.0.13 only the following librairies are loaded related to psych:
 "/home/dams/opt/pkgmgr/gems/gems/psych-2.0.13/lib/psych/exception.rb",
 "/home/dams/opt/pkgmgr/gems/gems/psych-2.0.13/lib/psych/syntax_error.rb",
 "/home/dams/opt/pkgmgr/gems/extensions/x86_64-linux/2.2.0/psych-2.0.13/psych.so",
 "/usr/lib/ruby/2.2.0/yaml.rb",

By contrast the others gems which don't have a problem with psych-2.13 like pry give 
 "/home/dams/opt/pkgmgr/gems/gems/psych-2.0.13/lib/psych/exception.rb",
 "/home/dams/opt/pkgmgr/gems/gems/psych-2.0.13/lib/psych/syntax_error.rb",
 "/home/dams/opt/pkgmgr/gems/extensions/x86_64-linux/2.2.0/psych-2.0.13/psych.so",
 "/home/dams/opt/pkgmgr/gems/gems/psych-2.0.13/lib/psych/omap.rb",
 "/home/dams/opt/pkgmgr/gems/gems/psych-2.0.13/lib/psych/set.rb",
 "/home/dams/opt/pkgmgr/gems/gems/psych-2.0.13/lib/psych/class_loader.rb",
 "/usr/lib/ruby/2.2.0/x86_64-linux/strscan.so",
[...]
 "/home/dams/opt/pkgmgr/gems/gems/psych-2.0.13/lib/psych/handlers/document_stream.rb",
 "/home/dams/opt/pkgmgr/gems/gems/psych-2.0.13/lib/psych.rb",
 "/usr/lib/ruby/2.2.0/yaml.rb",

So psych 2.13 is not fully loaded by webgen, but since it is called via "require 'yaml'" I don't see what's different from other gems. I have the same problem with psych 2.12, 2.11 and 2.10 (and I think psych 2.9), across different computers.

**Comment by DamienRobert** [comment]
Investigating further, the bug comes from the fact that "require 'yaml'" calls "require 'psych'".
Inside webgen, this loads  "/home/dams/opt/pkgmgr/gems/extensions/x86_64-linux/2.2.0/psych-2.0.13/psych.so" instead of  "/home/dams/opt/pkgmgr/gems/gems/psych-2.0.13/lib/psych.rb", I have no idea why!

This explain why the rest of the pscy library is not loaded, if I remove
 "/home/dams/opt/pkgmgr/gems/extensions/x86_64-linux/2.2.0/psych-2.0.13/psych.so"
everything works: "require psych" loads
"/home/dams/opt/pkgmgr/gems/gems/psych-2.0.13/lib/psych.rb",
which calls "require 'psych.so'" and finds it "psych.so" under
 "/home/dams/opt/pkgmgr/gems/gems/psych-2.0.13/lib/psych.rb".

**Comment by DamienRobert** [comment]
Ok I solved the bug even thought I don't understand what happened:
I managed to get it down to this line
      s.add_runtime_dependency(%q<kramdown>, ["~> 1.3"])
in webgen gemspec.
When commenting it, or replacing 1.3 by 1.7 the bug disappear.

Now I had both kramdown 1.4.2 and kramdown 1.7 installed. 'gem clean' would not remove kramdown 1.4.2 even though webgen is the only gem requiring it and '~>1.3' matches neither version.
Removing kramdown 1.4.2 solves the problem.

So the bug is probably due to some weird behaviour from rubygems which is confused by two versions not matching the '~>1.3' which somehow makes it load 'psych.so' directly instead of 'psych.rb'. I already spent too much time solving the bug, I don't think I'll try to look at rubygems source code to understand what happened and how I add both the most recent kramdown and version 1.4.2 which is not the one asked by webgen. The strangest thing is that this situation happened across several different computers!

I am thus closing this bug which does not seem related to webgen at all.

**Comment by gettalong** [comment]
Hi, I tried to reproduce the problem to see if I have to change the gemspec for webgen somehow. However, I was not able to reproduce the bug.

This is what I have installed:
~~~
$ gem list kramdown webgen psych

*** LOCAL GEMS ***

kramdown (1.7.0, 1.4.2)

*** LOCAL GEMS ***

webgen (1.4.0, 1.2.0)
webgen-font_awesome-bundle (1.0.0)
webgen-tipue_search-bundle (1.0.0)
webgen-zurb_foundation-bundle (1.0.0)

*** LOCAL GEMS ***

psych (2.0.13, 2.0.8)
~~~

Running the `webgen` command with this setup works just fine.

**Comment by DamienRobert** [comment]
Hi, this is probably a subtle bug anyway in rubygem since it is related to extensions. So maybe it only happens under specific versions of ruby/rubygem and the architecture of the computer. On my computer, after reinstalling kramdown 1.4.2:

~~~
$ gem list kramdown webgen psych

*** LOCAL GEMS ***

kramdown (1.8.0, 1.4.2)

*** LOCAL GEMS ***

webgen (1.4.0)
webgen-font_awesome-bundle (1.0.0)
webgen-templates-bundle (1.0.0)
webgen-zurb_foundation-bundle (1.0.0)

*** LOCAL GEMS ***

psych (2.0.13, 2.0.8)

$ webgen
webgen encountered a problem:
  private method `load' called for Psych:Module

$ ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]

$ uname -a
Linux feanor 4.1.4-1-ARCH #1 SMP PREEMPT Mon Aug 3 21:30:37 UTC 2015 x86_64 GNU/Linux
~~~

After removing kramdown 1.4.2 everything work again (this is quite mysterious)! Maybe when I have time I'll try to reproduce this in a clean wm.

**Comment by DamienRobert** [comment]
Hum this just happened again when I had both kramdown 1.8.0 and kramdown 1.9.0 installed. Removing the 1.8.0 version solved it once again.

**Comment by gettalong** [comment]
That is one strange bug... Maybe I should just remove the [pessimistic version constraint](http://guides.rubygems.org/patterns/#pessimistic-version-constraint)
